# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Automerge Dependabot PR

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  automerge:
    name: Automerge Dependabot PR (Merge Me!)
    runs-on: ubuntu-latest
    steps:
      - name: Merge me!
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: SQUASH
          PRESET: DEPENDABOT_MINOR
